# Generated by Django 4.0.4 on 2022-05-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_cartridgeproductnumber_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('company_contact_number', models.CharField(max_length=50)),
                ('notes_on_vendor', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cartridge',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.vendor'),
        ),
        migrations.AddField(
            model_name='printer',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.vendor'),
        ),
    ]
