# Generated by Django 4.0.4 on 2022-06-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_vendor_cartridge_vendor_printer_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridgeproductnumber',
            options={},
        ),
    ]
