# Generated by Django 4.0.4 on 2022-07-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_cartridge_date_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='owned_by',
        ),
    ]
