# Generated by Django 4.0.4 on 2022-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_printer_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='date_disposed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
